/**
 * Which tiles we take from the Dungeon Crawl Stone Soup pack (CC0).
 * Logical name → path inside Snowdrama/CC0-Dungeon-Pack.
 * The game only ever uses the logical names (see public/assets/tileset.json),
 * so another tileset can be plugged in by changing this file.
 */

/** Character builder ("Figur zusammenbauen"). Layers are drawn in DOLL_LAYERS order. */
export const DOLL: Record<string, Record<string, string>> = {
  base: {
    human_1: "player/base/human_male.png",
    human_2: "player/base/human_female.png",
    elf_1: "player/base/elf_male.png",
    elf_2: "player/base/elf_female.png",
    dwarf_1: "player/base/dwarf_male.png",
    dwarf_2: "player/base/dwarf_female.png",
    halfling_1: "player/base/halfling_male.png",
    halfling_2: "player/base/halfling_female.png",
  },
  cloak: {
    red: "player/cloak/red.png",
    blue: "player/cloak/blue.png",
    green: "player/cloak/green.png",
    black: "player/cloak/black.png",
    white: "player/cloak/white.png",
    yellow: "player/cloak/yellow.png",
  },
  boots: {
    brown: "player/boots/middle_brown.png",
    gray: "player/boots/middle_gray.png",
    short: "player/boots/short_brown.png",
  },
  legs: {
    brown: "player/legs/pants_brown.png",
    black: "player/legs/pants_black.png",
    blue: "player/legs/pants_blue.png",
    metal: "player/legs/metal_gray.png",
    armor: "player/legs/leg_armor_0.png",
  },
  body: {
    chainmail: "player/body/chainmail.png",
    plate: "player/body/plate.png",
    half_plate: "player/body/half_plate.png",
    scalemail: "player/body/scalemail.png",
    leather: "player/body/leather_armor.png",
    leather_green: "player/body/leather_green.png",
    jacket: "player/body/jacket_stud.png",
    robe_blue: "player/body/robe_blue.png",
    robe_red: "player/body/robe_red.png",
    robe_green: "player/body/robe_green.png",
    robe_white: "player/body/robe_white.png",
    robe_purple: "player/body/robe_purple.png",
    shirt: "player/body/shirt_white_1.png",
  },
  beard: {
    short_black: "player/beard/short_black.png",
    short_red: "player/beard/short_red.png",
    short_yellow: "player/beard/short_yellow.png",
    short_white: "player/beard/short_white.png",
    long_black: "player/beard/long_black.png",
    long_red: "player/beard/long_red.png",
    long_white: "player/beard/long_white.png",
  },
  hair: {
    short_black: "player/hair/short_black.png",
    short_red: "player/hair/short_red.png",
    short_yellow: "player/hair/short_yellow.png",
    short_white: "player/hair/short_white.png",
    long_black: "player/hair/long_black.png",
    long_red: "player/hair/long_red.png",
    long_yellow: "player/hair/long_yellow.png",
    long_white: "player/hair/long_white.png",
    pigtails: "player/hair/pigtails_brown.png",
    ponytail: "player/hair/ponytail_yellow.png",
    knot: "player/hair/knot_red.png",
    brown: "player/hair/brown_1.png",
  },
  head: {
    helm: "player/head/helm_plume.png",
    iron: "player/head/iron_1.png",
    viking: "player/head/viking_brown_1.png",
    wizard: "player/head/wizard_blue.png",
    wizard_red: "player/head/wizard_red.png",
    hood: "player/head/hood_green.png",
    hood_red: "player/head/hood_red.png",
    crown: "player/head/crown_gold_1.png",
  },
  weapon: {
    longsword: "player/hand_right/long_sword.png",
    greatsword: "player/hand_right/great_sword.png",
    rapier: "player/hand_right/rapier.png",
    shortsword: "player/hand_right/short_sword.png",
    dagger: "player/hand_right/dagger.png",
    mace: "player/hand_right/mace.png",
    hammer: "player/hand_right/hammer.png",
    axe: "player/hand_right/hand_axe.png",
    battleaxe: "player/hand_right/battleaxe.png",
    spear: "player/hand_right/spear.png",
    staff: "player/hand_right/quarterstaff.png",
    magestaff: "player/hand_right/staff_mage.png",
    bow: "player/hand_right/bow.png",
    crossbow: "player/hand_right/crossbow.png",
  },
  shield: {
    kite: "player/hand_left/shield_kite_1.png",
    knight: "player/hand_left/shield_knight_blue.png",
    round: "player/hand_left/shield_round_1.png",
    buckler: "player/hand_left/buckler_round_2.png",
    holy: "player/hand_left/shield_holy.png",
  },
};

/** Monster tiles by SRD monster ID. */
export const MONSTERS: Record<string, string> = {
  rat: "monster/animals/rat.png",
  "giant-rat": "monster/animals/grey_rat.png",
  "swarm-of-rats": "monster/animals/orange_rat.png",
  commoner: "monster/human.png",
  guard: "monster/holy/paladin.png",
  noble: "monster/unique/boris.png",
  ogre: "monster/ogre.png",
  "red-dragon-wyrmling": "monster/fire_drake.png",
  kobold: "monster/kobold.png",
  wolf: "monster/animals/wolf.png",
  "dire-wolf": "monster/animals/war_dog.png",
  bandit: "monster/unique/harold.png",
  "bandit-captain": "monster/unique/frances.png",
  thug: "monster/unique/edmund.png",
  knight: "monster/death_knight.png",
  veteran: "monster/unique/frederick.png",
  scout: "monster/elf.png",
  mage: "monster/unique/eustachio.png",
  goblin: "monster/goblin.png",
  cultist: "monster/necromancer.png",
  "cult-fanatic": "monster/enchantress_human.png",
  spy: "monster/unique/donald.png",
  priest: "monster/unique/francis.png",
  "swarm-of-bats": "monster/animals/bat.png",
  "werewolf-hybrid": "monster/gnoll.png",
  "green-hag": "monster/unique/agnes.png",
  ghost: "monster/undead/ghost.png",
  specter: "monster/undead/silent_spectre.png",
  skeleton: "monster/undead/skeletal_warrior.png",
  zombie: "monster/undead/zombies/zombie_small.png",
  ghoul: "monster/undead/ghoul.png",
  "giant-spider": "monster/animals/wolf_spider.png",
};

/** Everything else: dungeon, items, effects. Filled in phase A3. */
export const MISC: Record<string, string> = {};
