/**
 * Which tiles we take from the Dungeon Crawl Stone Soup pack (CC0).
 * Logical name → path inside Snowdrama/CC0-Dungeon-Pack.
 * The game only ever uses the logical names (see public/assets/tileset.json),
 * so another tileset can be plugged in by changing this file.
 */

/** Character builder ("Figur zusammenbauen"). Layers are drawn in DOLL_LAYERS order. */
export const DOLL: Record<string, Record<string, string>> = {
  base: {
    human_1: "player/base/human_male.png",
    human_2: "player/base/human_female.png",
    elf_1: "player/base/elf_male.png",
    elf_2: "player/base/elf_female.png",
    dwarf_1: "player/base/dwarf_male.png",
    dwarf_2: "player/base/dwarf_female.png",
    halfling_1: "player/base/halfling_male.png",
    halfling_2: "player/base/halfling_female.png",
  },
  cloak: {
    red: "player/cloak/red.png",
    blue: "player/cloak/blue.png",
    green: "player/cloak/green.png",
    black: "player/cloak/black.png",
    white: "player/cloak/white.png",
    yellow: "player/cloak/yellow.png",
  },
  boots: {
    brown: "player/boots/middle_brown.png",
    gray: "player/boots/middle_gray.png",
    short: "player/boots/short_brown.png",
  },
  legs: {
    brown: "player/legs/pants_brown.png",
    black: "player/legs/pants_black.png",
    blue: "player/legs/pants_blue.png",
    metal: "player/legs/metal_gray.png",
    armor: "player/legs/leg_armor_0.png",
  },
  body: {
    chainmail: "player/body/chainmail.png",
    plate: "player/body/plate.png",
    half_plate: "player/body/half_plate.png",
    scalemail: "player/body/scalemail.png",
    leather: "player/body/leather_armor.png",
    leather_green: "player/body/leather_green.png",
    jacket: "player/body/jacket_stud.png",
    robe_blue: "player/body/robe_blue.png",
    robe_red: "player/body/robe_red.png",
    robe_green: "player/body/robe_green.png",
    robe_white: "player/body/robe_white.png",
    robe_purple: "player/body/robe_purple.png",
    shirt: "player/body/shirt_white_1.png",
  },
  beard: {
    short_black: "player/beard/short_black.png",
    short_red: "player/beard/short_red.png",
    short_yellow: "player/beard/short_yellow.png",
    short_white: "player/beard/short_white.png",
    long_black: "player/beard/long_black.png",
    long_red: "player/beard/long_red.png",
    long_white: "player/beard/long_white.png",
  },
  hair: {
    short_black: "player/hair/short_black.png",
    short_red: "player/hair/short_red.png",
    short_yellow: "player/hair/short_yellow.png",
    short_white: "player/hair/short_white.png",
    long_black: "player/hair/long_black.png",
    long_red: "player/hair/long_red.png",
    long_yellow: "player/hair/long_yellow.png",
    long_white: "player/hair/long_white.png",
    pigtails: "player/hair/pigtails_brown.png",
    ponytail: "player/hair/ponytail_yellow.png",
    knot: "player/hair/knot_red.png",
    brown: "player/hair/brown_1.png",
  },
  head: {
    helm: "player/head/helm_plume.png",
    iron: "player/head/iron_1.png",
    viking: "player/head/viking_brown_1.png",
    wizard: "player/head/wizard_blue.png",
    wizard_red: "player/head/wizard_red.png",
    hood: "player/head/hood_green.png",
    hood_red: "player/head/hood_red.png",
    crown: "player/head/crown_gold_1.png",
  },
  weapon: {
    longsword: "player/hand_right/long_sword.png",
    greatsword: "player/hand_right/great_sword.png",
    rapier: "player/hand_right/rapier.png",
    shortsword: "player/hand_right/short_sword.png",
    dagger: "player/hand_right/dagger.png",
    mace: "player/hand_right/mace.png",
    hammer: "player/hand_right/hammer.png",
    axe: "player/hand_right/hand_axe.png",
    battleaxe: "player/hand_right/battleaxe.png",
    spear: "player/hand_right/spear.png",
    staff: "player/hand_right/quarterstaff.png",
    magestaff: "player/hand_right/staff_mage.png",
    bow: "player/hand_right/bow.png",
    crossbow: "player/hand_right/crossbow.png",
  },
  shield: {
    kite: "player/hand_left/shield_kite_1.png",
    knight: "player/hand_left/shield_knight_blue.png",
    round: "player/hand_left/shield_round_1.png",
    buckler: "player/hand_left/buckler_round_2.png",
    holy: "player/hand_left/shield_holy.png",
  },
};

/** Monster tiles by SRD monster ID. */
export const MONSTERS: Record<string, string> = {
  rat: "monster/animals/rat.png",
  "giant-rat": "monster/animals/grey_rat.png",
  "swarm-of-rats": "monster/animals/orange_rat.png",
  commoner: "monster/human.png",
  guard: "monster/holy/paladin.png",
  noble: "monster/unique/boris.png",
  ogre: "monster/ogre.png",
  "red-dragon-wyrmling": "monster/fire_drake.png",
  kobold: "monster/kobold.png",
  wolf: "monster/animals/wolf.png",
  "dire-wolf": "monster/animals/war_dog.png",
  bandit: "monster/unique/harold.png",
  "bandit-captain": "monster/unique/frances.png",
  thug: "monster/unique/edmund.png",
  knight: "monster/death_knight.png",
  veteran: "monster/unique/frederick.png",
  scout: "monster/elf.png",
  mage: "monster/unique/eustachio.png",
  goblin: "monster/goblin.png",
  cultist: "monster/necromancer.png",
  "cult-fanatic": "monster/enchantress_human.png",
  spy: "monster/unique/donald.png",
  priest: "monster/unique/francis.png",
  "swarm-of-bats": "monster/animals/bat.png",
  "werewolf-hybrid": "monster/gnoll.png",
  "green-hag": "monster/unique/agnes.png",
  ghost: "monster/undead/ghost.png",
  specter: "monster/undead/silent_spectre.png",
  skeleton: "monster/undead/skeletal_warrior.png",
  zombie: "monster/undead/zombies/zombie_small.png",
  ghoul: "monster/undead/ghoul.png",
  "giant-spider": "monster/animals/wolf_spider.png",
};

/** "name.0" … "name.(n-1)" from "dir/prefix_<start+i>.png". */
function variants(name: string, prefix: string, count: number, start = 0): Record<string, string> {
  return Object.fromEntries(Array.from({ length: count }, (_, i) => [`${name}.${i}`, `${prefix}_${start + i}.png`]));
}

/**
 * Map tiles. Floors and walls come in themes (castle, cave, …) with a few variants each,
 * so rooms don't look like wallpaper.
 */
export const MISC: Record<string, string> = {
  // Floors
  ...variants("floor.grass", "dungeon/floor/grass/grass", 3),
  "floor.grass.3": "dungeon/floor/grass/grass_flowers_yellow_1.png",
  "floor.grass.4": "dungeon/floor/grass/grass_flowers_red_1.png",
  "floor.grass.5": "dungeon/floor/grass/grass_flowers_blue_1.png",
  ...variants("floor.path", "dungeon/floor/grass/grass0-dirt-mix", 3, 1),
  ...variants("floor.dirt", "dungeon/floor/dirt", 3),
  ...variants("floor.castle", "dungeon/floor/rect_gray", 4),
  ...variants("floor.marble", "dungeon/floor/white_marble", 4),
  ...variants("floor.cave", "dungeon/floor/pebble_brown", 4),
  ...variants("floor.lair", "dungeon/floor/volcanic_floor", 4),
  ...variants("floor.crypt", "dungeon/floor/tomb", 4),
  ...variants("floor.village", "dungeon/floor/grey_dirt", 4),
  ...variants("floor.sand", "dungeon/floor/sand", 4, 1),
  ...variants("floor.mud", "dungeon/floor/mud", 4),
  ...variants("floor.stone", "dungeon/floor/limestone", 4),
  // Walls
  ...variants("wall.castle", "dungeon/wall/stone_brick", 4, 1),
  ...variants("wall.brick", "dungeon/wall/brick_brown", 4),
  ...variants("wall.cave", "dungeon/wall/brick_dark", 4),
  ...variants("wall.lair", "dungeon/wall/volcanic_wall", 4),
  ...variants("wall.crypt", "dungeon/wall/tomb", 4),
  ...variants("wall.hedge", "dungeon/wall/wall_vines", 4),
  ...variants("wall.stone", "dungeon/wall/stone_gray", 4),
  ...variants("wall.church", "dungeon/wall/church", 4),
  // Water (a stone bridge is drawn with castle floor)
  "water.deep": "dungeon/water/deep_water.png",
  "water.deep.1": "dungeon/water/deep_water_2.png",
  "water.shallow": "dungeon/water/shallow_water.png",
  "water.shallow.1": "dungeon/water/shallow_water_2.png",
  // Objects
  "tree.0": "dungeon/trees/tree_1_red.png",
  "tree.1": "dungeon/trees/tree_2_yellow.png",
  "tree.2": "dungeon/trees/mangrove_1.png",
  "tree.3": "dungeon/trees/mangrove_2.png",
  "tree.4": "dungeon/trees/tree_1_yellow.png",
  "door.closed": "dungeon/doors/closed_door.png",
  "door.open": "dungeon/doors/open_door.png",
  "gate.closed": "dungeon/doors/gate_closed_middle.png",
  "gate.open": "dungeon/doors/gate_open_middle.png",
  "chest.closed": "dungeon/chest_2_closed.png",
  "chest.open": "dungeon/chest_2_open.png",
  "chest.gold": "dungeon/chest.png",
  box: "dungeon/large_box.png",
  boulder: "dungeon/boulder.png",
  ...variants("torch", "dungeon/wall/torches/torch", 5),
  banner: "dungeon/wall/banners/banner_1.png",
  "statue.sword": "dungeon/statues/statue_sword.png",
  "statue.dragon": "dungeon/statues/statue_dragon.png",
  "statue.hero": "dungeon/statues/statue_ancient_hero.png",
  "statue.princess": "dungeon/statues/statue_princess.png",
  column: "dungeon/statues/crumbled_column.png",
  pedestal: "dungeon/statues/pedestal.png",
  altar: "dungeon/altars/altar_shining_one.png",
  throne: "dungeon/statues/statue_bases.png",
  "stairs.down": "dungeon/gateways/stone_stairs_down.png",
  "stairs.up": "dungeon/gateways/stone_stairs_up.png",
  arch: "dungeon/gateways/stone_arch.png",
  "trap.arrow": "dungeon/traps/trap_arrow.png",
  "trap.plate": "dungeon/traps/pressure_plate.png",
  "trap.net": "dungeon/traps/trap_net.png",
  fountain: "dungeon/blue_fountain.png",
  "fountain.dry": "dungeon/dry_fountain.png",
  // Items on the ground
  "item.potion": "item/potion/ruby.png",
  "item.gold": "item/gold/gold_pile_10.png",
  "item.key": "item/misc/key.png",
  "item.lamp": "item/misc/misc_lantern.png",
  "item.lance": "player/hand_right/lance.png",
  // Decals and effects
  ...variants("blood", "misc/blood/blood_puddle_red", 2, 1),
  ...variants("fire", "effect/cloud_fire", 3),
  ...variants("flame", "effect/flame", 3),
  "magic.bolt": "effect/magic_bolt_1.png",
  ...variants("sparkle", "effect/gold_sparkles", 3, 1),
  // Small animals that only liven up the map (no rules).
  "critter.rat": "monster/animals/grey_rat.png",
  "critter.butterfly.0": "monster/animals/butterfly_1.png",
  "critter.butterfly.1": "monster/animals/butterfly_3.png",
  "critter.butterfly.2": "monster/animals/butterfly_6.png",
  "critter.bat": "monster/animals/bat.png",
  "critter.sheep": "monster/animals/sheep.png",
  "critter.hog": "monster/animals/hog.png",
  "critter.dog": "monster/animals/hound.png",
  "critter.spider": "monster/animals/spider.png",
  "critter.frog": "monster/animals/giant_frog.png",
  "critter.snake": "monster/animals/small_snake.png",
  "critter.moth": "monster/animals/ghost_moth.png",
  // Interactive objects drawn for this game (scripts/assets/custom, CC0).
  barrel: "custom:barrel.png",
  "lever.off": "custom:lever_off.png",
  "lever.on": "custom:lever_on.png",
  chandelier: "custom:chandelier.png",
  "chandelier.down": "custom:chandelier_down.png",
  "secret.plate": "custom:loose_plate.png",
  "secret.runes": "custom:runes.png",
  "secret.found": "custom:secret_found.png",
  cauldron: "custom:cauldron.png",
  campfire: "custom:campfire.png",
};
